### ISSUE TITLE
Setup a persistent event store

### ISSUE THREAD

**Issue by github1** [github1/ccnext#17]
Currently the events are stored in memory. See https://github.com/github1/ccnext/blob/master/platform/src/impl/runtime/es.ts#L72 for where the eventstore is initialized and https://github.com/adrai/node-eventstore for persistence options.

**Comment by ELWOOD29** [comment]
Struggling with this one slightly in that to configure it for dynamodb, you need to pass in options like so :
```
var es = require('eventstore')({
    type: 'dynamodb'
});
```
then when I run `./run.sh` 3 tables are provisioned in dynamodb

but this syntax isn't consistent with the rest of the project, and I can't find anywhere how to pass options in when importing a function module in typescript/es6.

Any ideas?

**Comment by ELWOOD29** [comment]
closed via c8d7d52341ccbe5cc1257eceb82f822116a36033
